version: 2

models:
  - name: fact_orders
    description: "Tabla de hechos de órdenes"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id

      - name: product_id
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_id
